"""Arabic normalization used ONLY for the hidden search index.

The canonical text shown to users is never passed through these functions.
The Dart implementation in lib/core/arabic/arabic_normalizer.dart must stay
behaviour-identical; tool/import/normalization_vectors.json (generated by
build_database.py) is checked by both test suites.

Rules (applied in this order):
  1. Remove harakat/tanween/shadda/sukun and Quranic annotation marks
     (U+0610–U+061A, U+064B–U+065F, U+0670, U+06D6–U+06DC, U+06DF–U+06E8,
     U+06EA–U+06ED, U+08D3–U+08E1, U+08E3–U+08FF) and tatweel (U+0640).
  2. أ إ آ ٱ -> ا ; ى -> ي ; Arabic-Indic and Extended Arabic-Indic digits
     -> ASCII digits.
  3. Broad mode only: ة -> ه.
  4. Every run of characters that are not Arabic letters (U+0621–U+063A,
     U+0641–U+064A), ASCII letters or digits becomes one space; the result
     is trimmed.
"""

from __future__ import annotations

import re

_DIACRITICS = re.compile(
    "[ؐ-ًؚ-ٰٟۖ-ۜ۟-۪ۨ-ۭ࣓-ࣣ࣡-ࣿـ]"
)
_LETTER_MAP = str.maketrans(
    {
        "أ": "ا",  # أ
        "إ": "ا",  # إ
        "آ": "ا",  # آ
        "ٱ": "ا",  # ٱ
        "ى": "ي",  # ى -> ي
        **{chr(0x0660 + i): str(i) for i in range(10)},
        **{chr(0x06F0 + i): str(i) for i in range(10)},
    }
)
_TA_MARBUTA = str.maketrans({"ة": "ه"})  # ة -> ه
_NON_WORD = re.compile("[^0-9A-Za-zء-غف-ي]+")


def normalize(text: str, *, broad: bool = False) -> str:
    """Return a space-separated, search-only normalized form of ``text``."""
    t = _DIACRITICS.sub("", text).translate(_LETTER_MAP)
    if broad:
        t = t.translate(_TA_MARBUTA)
    return _NON_WORD.sub(" ", t).strip()


def arabic_digits_to_int(text: str) -> int | None:
    """Parse a number written with Arabic-Indic or Western digits."""
    digits = text.translate(_LETTER_MAP).strip()
    return int(digits) if digits.isascii() and digits.isdigit() else None
